---
  #----------------------------------------------------------------------------#
  # Traefik
  # https://doc.traefik.io/traefik/getting-started/quick-start/
  #----------------------------------------------------------------------------#
version: '3.9'

services:
  reverse-proxy:
    image: "traefik:${TRAEFIK_VERSION}"
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env