---
#----------------------------------------------------------------------------#
# Yacht
#----------------------------------------------------------------------------#
version: '3.9'

services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    restart: unless-stopped
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ADMIN_EMAIL: $ADMIN_EMAIL
    env_file: .env
    network_mode: host
    labels:
      - traefik.enable=true
      - traefik.http.routers.yacht.service=yacht
      - "traefik.http.routers.yacht.rule=Host(`yacht.services.viper`)"
      - traefik.http.services.yacht.loadbalancer.server.port=8000

volumes:
  yacht:

