---
version: '3.9'

services:
  yacht:
    image: 'selfhostedpro/yacht'
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ADMIN_EMAIL: $ADMIN_EMAIL

volumes:
  yacht: